#Main
FRONT_PAGE = '//nav//a[2]/img'
#Login
LOGIN_BUTTON = '//a[contains(@class, "login")]'
USERNAME_FIELD = '//*[@id="username"]'
PASSWORD_FIELD = '//*[@id="password"]'
LOGIN_BUTTON2 =  '//input[@value= "Login"]'
LOG_OUT_ELEMENT = '//a[contains(text(), "Log out")]'
#Emailgroup
ALL_USERS_PAGE = 'body > vibe-app > nav > a:nth-child(4)'
EMAIL_GROUPS_BUTTON = '//*[@id="masterContainer"]/vibe-organization/div/div[3]/vibe-organization-emails/div[1]'
ADD_NEW_EMAIL_GROUP = '//*[@id="masterContainer"]/vibe-organization/div/div[3]/vibe-organization-emails/div[2]/a'
NEW_EMAIL_GROUP_NAME_FIELD = '//*[@id="mat-mdc-dialog-0"]/div/div/vibe-modal-prompt/vibe-modal-borders/mat-dialog-content/div/div/div[2]/input'
NEW_EMAIL_GROUP_OK = '//*[@id="mat-mdc-dialog-0"]/div/div/vibe-modal-prompt/vibe-modal-borders/mat-dialog-content/div/div/div[3]/button[1]'
ALL_USERS_STATE = 'text="Testaus"'
RENAME_EMAIL_GROUP = 'xpath=(//*[@id="masterContainer"]//vibe-organization-emails//a[1]/i)[last()]'
RENAME_EMAIL_GROUP_FIELD = 'xpath=//vibe-modal-prompt//input'
RENAME_EMAIL_GROUP_OK = 'xpath=//vibe-modal-prompt//button[1]'
REMOVE_EMAIL_GROUP_BUTTON = '//*[@id="masterContainer"]/vibe-organization/div/div[3]/vibe-organization-emails/div[2]/div[2]/div/div[41]/a[4]/i'
REMOVE_EMAIL_GROUP_OK = '//*[@id="mat-mdc-dialog-1"]/div/div/vibe-modal-confirm/vibe-modal-borders/mat-dialog-content/div/div/div[2]/button[1]'
LAST_EMAIL_GROUP = '//*[@id="masterContainer"]/vibe-organization/div/div[3]/vibe-organization-emails/div[2]/div[2]/div/div[last()]'
ADD_EMAILS_BUTTON = 'xpath=//*[@id="masterContainer"]/vibe-organization/div/div[3]/vibe-organization-emails/div[2]/div[2]/div/div[last()]/vibe-email-entry/div/div/a'
EMAIL_FIELD = 'xpath=(//vibe-email-entry-modal//textarea)[last()]'
EMAIL_ADD_BUTTON = 'xpath=(//vibe-email-entry-modal//button)[last()]'
#QWL_Poll
ADD_NEW_PROJECT = '(//a[contains(@class, "add-project")])[1]'
ADD_PROJECT_NAME = '//*[@id="addProjectName"]'
CREATE_QWL_POLL_BUTTON = 'text="Create a QWL poll"'
QWL_TYPE_OPTIONS = '//select[option[@value="complete"]]'
ORGANIZATION_TYPE_OPTIONS = '//select[option[contains(text(),"traditional")]]'
HIDE_VECTOR_GRAPHS_CHECKBOX = '//input[@type="checkbox"]'
#Custom_Poll
CREATE_CUSTOM_POLL_BUTTON = 'text="Create a custom poll"'
ADD_QUESTIONS_BUTTON = '//a[contains(text(),"Add questions")]'
TYPE_QUESTIONS_FIELD = '//*[@id="customQuestionText"]'
ADD_QUESTIONS_BUTTON2 = '//button[contains(text(),"Add questions")]'
#create360poll
CREATE_360_POLL_BUTTON = '//button[normalize-space()="Create a 360 feedback poll"]'
ADD_QUESTION_BUTTON = '//vibe-settings-resources//a[contains(text(), "Add")]'
SELECT_NEW_QUESTION = '//select[@id="readyMade"]'
CLICK_FIRST_CHOICE = '(//a[@class="mat-mdc-tooltip-trigger btn btn-minimal"][normalize-space()="Select"])[1]'
ADD_SELECTED_QUESTION = '//button[normalize-space()="Add 1 selected question"]'
#answercustompoll
WORST_ICON = '//div[contains(@class,"question") and contains(@class, "fullHeight") and not(@hidden)]//a[1]//img'
POOR_ICON = '//div[contains(@class,"question") and contains(@class, "fullHeight") and not(@hidden)]//a[2]//img'
AVERAGE_ICON = '//div[contains(@class,"question") and contains(@class, "fullHeight") and not(@hidden)]//a[3]//img'
GOOD_ICON = '//div[contains(@class,"question") and contains(@class, "fullHeight") and not(@hidden)]//a[4]//img'
BEST_ICON = '//div[contains(@class,"question") and contains(@class, "fullHeight") and not(@hidden)]//a[5]//img'

